import { ethers } from "ethers";
import contractData from "../contractData.json"; // ✅ auto-generated by deploy.js

export async function getContract() {
  if (typeof window === "undefined" || !window.ethereum) {
    throw new Error("MetaMask not detected");
  }

  const provider = new ethers.BrowserProvider(window.ethereum);
  const signer = await provider.getSigner();

  return new ethers.Contract(contractData.address, contractData.abi, signer);
}
